name: bitrisesample
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.6 # Only if you're using it

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
